### ISSUE TITLE
bad  access on mac app

### ISSUE THREAD

**Issue by mattshepherd** [r0th/AirplayKit#1]
After building the mac app(AirplayKit) I get an EXC_BAD_ACCESS error after it connects to the apple tv. It's on line 3914 on AsyncSocket.m

**Comment by DaronLord** [comment]
I have received the same error on the same line.

**Comment by jeffmcfadden** [comment]
+1. Looks like the AKAirplayManager is being dealloc-ed from somewhere right before the attempted message send by the socket. Haven't yet been able to track down the cause of the dealloc — seems like it's being retained properly, yet you can see that it's a zombie when you run in the profiler.

**Comment by jeffmcfadden** [comment]
Found a solution.

Comment out line 104 of AKAirplayManager.m:  
`//[device release];`

**Comment by mattshepherd** [comment]
that did fix it, i need to check if anything is being leaked now, but no longer crashing.
