### ISSUE TITLE
NSNetServiceBrowser never finds any AirPlay device

### ISSUE THREAD

**Issue by jeena** [r0th/AirplayKit#2]
I run the AirplayKit mac app but NSNetServiceBrowser never finds any AirPlay device therefore netServiceBrowser:didFindService:moreComing: never gets called.

I have a Airport Express and am able to play Music from my iTunes on it, iTunes discovers it and can use it. Am I doing something wrong?

**Comment by r0th** [comment]
The audio implementation of Airplay is different from video/images, and is not supported by AirplayKit.
