### ISSUE TITLE
AirPlayKit Not working anymore: Async Socket issue?

### ISSUE THREAD

**Issue by loretoparisi** [r0th/AirplayKit#4]
The AirPlayKit does not work anymore with AppleTV3,1 devices
It connects to the AppleTV net service, but no async socket delegate seems to be called.
It seems to be a AsyncSocket issue, more than a AppleTV protocol issues. In fact other frameworks like ConnectSDK by LG works ok ( https://github.com/ConnectSDK/Connect-SDK-iOS ) or Erica Sadun AirFlick ( http://ericasadun.com/ftp/AirPlay/ )

AppleTV3,1 specifications are:

{
    deviceid = "xxxxx";
    features = "0x5A7FFFF7,0xE";
    flags = 0x44;
    model = "AppleTV3,1";
    pi = "43f884bc-eb56-459d-a307-9cce844f86bf";
    pk = 8b197524a8f78819b8e64b8d8cd4a70faec1b49317e517fb81f624628a313a39;
    srcvers = "220.68";
    vv = 2;
}

**Comment by r0th** [comment]
Yeah, this project was just an experiment with the initial Airplay implementation. I'm not planning on maintaining it any further as hardware and OS updates will break it.

**Comment by loretoparisi** [comment]
I see! The curios thing is that it worked for years until an update of the AppleTV3,1. More strange is that the PHP implementation (that apparently is the same) works ( https://github.com/jamesdlow/open-airplay/issues/8 ). A simple shell cURL command will not (the same that was working before...)

**Comment by ChrisHughes** [comment]
I took a look at jamesdlow/open-airplay#8 and compared the two via wireshark. Turns out to make AirplayKit work, all you have to do is comment out the line

> [self.connectedDevice sendReverse]

in AKAirplayManager.m. It is not required to perform a successful connection it seems.

Hope this helps!

**Comment by loretoparisi** [comment]
@ChrisHughes wow, great finding, I will check it out :+1:
